// Module Image / vidéo en anglais : texte français (index.html, app.js, media.js) → anglais.
I18N.add({
  // aperçu
  'Aperçu': 'Preview',
  'Position rapide': 'Quick position',
  'Écouter': 'Listen',
  "Entendre le son dans l'aperçu. À l'écran, le son sort si « Son » est activé.": 'Hear the sound in the preview. On screen, sound plays when “Sound” is on.',
  'Rejouer': 'Replay',
  "Rejouer depuis le début, avec l'animation d'entrée": 'Replay from the start, with the entrance animation',
  'Glisse une image, un GIF ou une vidéo': 'Drop an image, a GIF or a video',
  'PNG · JPG · GIF · WebP · MP4 · WebM · MOV': 'PNG · JPG · GIF · WebP · MP4 · WebM · MOV',
  'Choisir un fichier…': 'Choose a file…',
  'Dépose pour importer': 'Drop to import',
  'Glisse le média pour le placer · tire le coin pour le redimensionner · Alt : sans aimant': 'Drag the media to place it · pull the corner to resize · Alt: no snapping',
  'Cadrage plein écran · passe en « Libre » pour déplacer le média': 'Full-screen framing · switch to “Free” to move the media',

  // média et bibliothèque
  'Média': 'Media',
  'Choisir…': 'Choose…',
  'Remplacer…': 'Replace…',
  'Aucun média': 'No media',
  'Importe un fichier ou choisis-en un dans la bibliothèque.': 'Import a file or pick one from the library.',
  'Chargement…': 'Loading…',
  'Vidéo': 'Video',
  'Image': 'Image',
  'Image fixe': 'Still image',
  '{ext} animé': 'Animated {ext}',
  '{n} images': '{n} frames',
  'Ko': 'KB',
  'Mo': 'MB',
  'Découpe': 'Trim',
  'Tout': 'All',
  'Lire le fichier en entier': 'Play the whole file',
  'Début': 'Start',
  'Fin': 'End',
  'Bibliothèque': 'Library',
  '{n} fichier': '{n} file',
  '{n} fichiers': '{n} files',
  'Les fichiers importés restent ici, réutilisables dans toutes tes scènes.': 'Imported files stay here, reusable in all your scenes.',
  'Retirer de la bibliothèque': 'Remove from library',
  'Cliquer encore pour supprimer': 'Click again to delete',
  "Utilisé par {n} calque : retire-le de la scène d'abord.": 'Used by {n} layer: remove it from the scene first.',
  "Utilisé par {n} calques : retire-le de la scène d'abord.": 'Used by {n} layers: remove it from the scene first.',
  'Vidéo illisible : format ou codec non pris en charge': 'Unreadable video: unsupported format or codec',
  "Ce fichier ne contient pas d'image": 'This file contains no picture',
  'Image illisible : format non pris en charge': 'Unreadable image: unsupported format',
  'Lecture impossible': 'Cannot play',

  // lecture
  'Lecture': 'Playback',
  'Une fois': 'Once',
  'Boucle': 'Loop',
  'Boomerang': 'Boomerang',
  'Vitesse': 'Speed',
  'Passages': 'Repeats',
  'Pause': 'Pause',
  'À la fin': 'At the end',
  'Figer': 'Freeze',
  'Disparaître': 'Disappear',
  'Passages ∞ : sans fin. Pause : attente entre deux passages.': 'Repeats ∞: endless. Pause: wait between two plays.',
  "Le boomerang garde les images en mémoire : il est fait pour un extrait court. Réduis la découpe sous 10 s pour qu'il reste fluide.": 'Boomerang keeps frames in memory: it is meant for a short clip. Trim it under 10 s to keep it smooth.',
  'Durée': 'Duration',
  "∞ : l'image reste affichée. Sinon, elle disparaît après ce délai.": '∞: the image stays on screen. Otherwise it disappears after this delay.',
  'Choisis un média pour régler sa lecture.': 'Choose a media to set its playback.',

  // son
  'Son': 'Sound',
  'Volume': 'Volume',
  'Le boomerang est toujours muet.': 'Boomerang is always muted.',
  "Le son ne sort que de la scène à l'écran. L'aperçu reste muet, sauf avec « Écouter ».": 'Sound only plays from the scene on screen. The preview stays muted, except with “Listen”.',

  // cadrage
  'Cadrage': 'Framing',
  'Libre': 'Free',
  'Ajuster': 'Fit',
  'Remplir': 'Fill',
  'Taille et position libres': 'Free size and position',
  'Tout le média, aussi grand que possible': 'The whole media, as large as possible',
  "Couvre tout l'écran, quitte à rogner": 'Covers the whole screen, cropping if needed',
  'Taille': 'Size',
  'Rotation': 'Rotation',
  'Opacité': 'Opacity',
  'Coins': 'Corners',
  'Miroir': 'Mirror',
  'Ombre portée': 'Drop shadow',

  // animation
  'Animation': 'Animation',
  'Entrée': 'Entrance',
  'Directe': 'Instant',
  'Fondu': 'Fade',
  'Pop': 'Pop',
  'Montée': 'Rise',
  'Zoom': 'Zoom',
  'Glissé': 'Slide',
  'Mouvement': 'Motion',
  'Aucun': 'None',
  'Flotter': 'Float',
  'Pulsation': 'Pulse',
  'Balancier': 'Swing',
  'Toupie': 'Spin',
  'Vibration': 'Shake',
});
