// Module Caméra en anglais : texte français (index.html, app.js, cam.js) → anglais.
I18N.add({
  // aperçu
  'Aperçu': 'Preview',
  'Position rapide': 'Quick position',
  "Rejouer l'animation d'entrée": 'Replay the entrance animation',
  "Rejouer l'entrée": 'Replay entrance',
  'Réessayer': 'Retry',
  'Glisse la caméra pour la placer · tire le coin pour la redimensionner · Alt : sans aimant': 'Drag the camera to place it · pull the corner to resize · Alt: no snapping',
  'Cadrage plein écran · passe en « Libre » pour déplacer la caméra': 'Full-screen framing · switch to “Free” to move the camera',
  'Erreur': 'Error',
  'Ouverture…': 'Opening…',
  'i/s': 'fps',
  "En attente de l'iPhone": 'Waiting for the iPhone',
  "Scanne le QR code ci-dessous avec l'appareil photo de l'iPhone.": "Scan the QR code below with the iPhone's camera.",
  "Connexion à l'iPhone…": 'Connecting to the iPhone…',
  'Si rien ne vient, vérifie que Windows autorise SceneCue sur les réseaux privés.': 'If nothing shows up, check that Windows allows SceneCue on private networks.',
  'Si rien ne vient, vérifie que le pare-feu laisse passer le port {port}.': 'If nothing shows up, check that the firewall lets port {port} through.',
  'Le serveur ne démarre pas': "The server won't start",
  'Caméra indisponible': 'Camera unavailable',
  'Ouverture de la caméra…': 'Opening the camera…',

  // source
  'Source': 'Source',
  'iPhone (Wi-Fi)': 'iPhone (Wi-Fi)',
  'Caméra du PC': 'PC camera',
  'Caméra': 'Camera',
  'Caméra {n}': 'Camera {n}',
  'Actualiser la liste': 'Refresh the list',
  'Aucune caméra détectée': 'No camera detected',
  '{name} (débranchée)': '{name} (unplugged)',
  'Définition': 'Resolution',
  'Images/s': 'Frames/s',
  "Webcam, carte d'acquisition ou caméra virtuelle (Camo, Iriun…). Une autre application qui l'utilise déjà (Discord, OBS, Teams) peut la bloquer.": 'Webcam, capture card or virtual camera (Camo, Iriun…). Another application already using it (Discord, OBS, Teams) can block it.',
  'Avant': 'Front',
  'Arrière': 'Back',
  'Qualité': 'Quality',
  'Aucun téléphone : scanne le QR code': 'No phone: scan the QR code',
  'Téléphone injoignable (Safari en arrière-plan ?)': 'Phone unreachable (Safari in the background?)',
  'Téléphone': 'Phone',
  'Navigateur': 'Browser',
  "à l'écran": 'on screen',
  '{n} aperçu': '{n} preview',
  '{n} aperçus': '{n} previews',

  // connexion de l'iPhone
  "Connexion de l'iPhone": 'iPhone connection',
  "À scanner avec l'appareil photo de l'iPhone": "Scan with the iPhone's camera",
  'iPhone sur le <b>même Wi-Fi</b> que ce PC.': 'iPhone on the <b>same Wi-Fi</b> as this PC.',
  "Scanne le code avec l'<b>appareil photo</b>.": 'Scan the code with the <b>Camera</b> app.',
  '« Connexion non privée » : <b>Afficher les détails › visiter ce site web</b>.': '“Connection not private”: <b>Show Details › visit this website</b>.',
  'Touche <b>Démarrer</b> et autorise la caméra.': 'Tap <b>Start</b> and allow the camera.',
  'Copier': 'Copy',
  'Adresse copiée': 'Address copied',
  "Copie impossible : sélectionne l'adresse à la main.": 'Copy failed: select the address by hand.',
  'Carte réseau': 'Network adapter',
  'virtuelle': 'virtual',
  "Au premier lancement, Windows demande l'accès au réseau : autorise les <b>réseaux privés</b>.": 'On first launch, Windows asks for network access: allow <b>private networks</b>.',
  'Si un pare-feu est actif (ufw, firewalld…), ouvre-lui les ports <b>8443</b> et <b>8080</b>.': 'If a firewall is active (ufw, firewalld…), open ports <b>8443</b> and <b>8080</b> in it.',
  'démarrage…': 'starting…',
  'arrêté': 'stopped',
  'Serveur : {error}': 'Server: {error}',
  "Adresse http:// indisponible ({error}). L'adresse https:// fonctionne.": 'http:// address unavailable ({error}). The https:// address works.',
  "Aucune carte Wi-Fi ou Ethernet trouvée : branche le PC au même réseau que l'iPhone.": 'No Wi-Fi or Ethernet adapter found: connect the PC to the same network as the iPhone.',
  'Serveur indisponible hors de SceneCue': 'Server unavailable outside SceneCue',
  'SceneCue indisponible': 'SceneCue unavailable',

  // erreurs de la caméra du PC
  'Caméra déjà utilisée par une autre application (Discord, OBS, Teams…). Ferme-la puis clique « Réessayer ».': 'Camera already used by another application (Discord, OBS, Teams…). Close it, then click “Retry”.',
  'Caméra introuvable : rebranche-la ou choisis-en une autre.': 'Camera not found: plug it back in or choose another one.',
  'Windows bloque la caméra : Paramètres › Confidentialité › Caméra › autoriser les applications de bureau.': 'Windows blocks the camera: Settings › Privacy › Camera › allow desktop apps.',
  "Le système refuse l'accès à la caméra.": 'The system denies access to the camera.',
  "La caméra s'est arrêtée (débranchée ?).": 'The camera stopped (unplugged?).',

  // cadrage
  'Cadrage': 'Framing',
  'Libre': 'Free',
  'Ajuster': 'Fit',
  'Remplir': 'Fill',
  'Taille et position libres': 'Free size and position',
  "Toute l'image, aussi grande que possible": 'The whole picture, as large as possible',
  "Couvre tout l'écran, quitte à rogner": 'Covers the whole screen, cropping if needed',
  'Taille': 'Size',
  'Rotation': 'Rotation',
  'Opacité': 'Opacity',
  'Miroir': 'Mirror',
  'Ombre portée': 'Drop shadow',

  // forme
  'Forme et recadrage': 'Shape and crop',
  'Rectangle': 'Rectangle',
  'Arrondi': 'Rounded',
  'Cercle': 'Circle',
  'Coins': 'Corners',
  'Image': 'Source',
  "Format de l'image reçue": 'Format of the received picture',
  'Paysage': 'Landscape',
  'Classique': 'Classic',
  'Carré': 'Square',
  'Portrait (téléphone debout)': 'Portrait (phone upright)',
  'Zoom': 'Zoom',
  'Horizontal': 'Horizontal',
  'Vertical': 'Vertical',
  'Recadre en zoomant puis en déplaçant le point de visée. Double-clic sur un curseur : valeur par défaut.': 'Crop by zooming in, then moving the focus point. Double-click a slider: default value.',

  // bordure et animation
  'Bordure': 'Border',
  'Épaisseur': 'Width',
  'Couleur': 'Color',
  "Animation d'entrée": 'Entrance animation',
  'Directe': 'Instant',
  'Fondu': 'Fade',
  'Pop': 'Pop',
  'Montée': 'Rise',
  'Glissé': 'Slide',
});
