// Page du téléphone en anglais : texte français (index.html, phone.js, messages de Régie) → anglais.
I18N.add({
  'Régie · Caméra': 'Régie · Camera',
  'Prêt': 'Ready',
  'Connexion…': 'Connecting…',
  "À l'écran": 'On screen',
  'Aperçu dans Régie': 'Preview in Régie',
  'En attente de Régie': 'Waiting for Régie',
  "La caméra s'affichera ici": 'The camera will show up here',
  'Code affiché dans Régie': 'Code shown in Régie',
  'Démarrer la caméra': 'Start the camera',
  'Arrêter': 'Stop',
  'Avant': 'Front',
  'Arrière': 'Back',
  "Garde Safari ouvert, au premier plan : iOS coupe la caméra dès que tu changes d'app ou que l'écran se verrouille.": 'Keep Safari open in the foreground: iOS cuts the camera as soon as you switch apps or the screen locks.',
  'Branche le téléphone si tu streames longtemps.': 'Plug the phone in if you stream for a long time.',
  'Accès à la caméra refusé. Réglages › Safari › Caméra › Autoriser, puis recharge la page.': 'Camera access denied. Settings › Safari › Camera › Allow, then reload the page.',
  'La caméra est déjà utilisée par une autre app (appel, FaceTime…).': 'The camera is already used by another app (call, FaceTime…).',
  'Aucune caméra trouvée.': 'No camera found.',
  'Un autre appareil a pris le relais. Touche « Démarrer » pour reprendre la main.': 'Another device took over. Tap “Start” to take back control.',
  "La caméra s'est arrêtée (appel, autre app…). Reviens sur cette page pour la relancer.": 'The camera stopped (call, another app…). Come back to this page to restart it.',
  'Entre le code affiché dans Régie, ou scanne son QR code.': 'Enter the code shown in Régie, or scan its QR code.',
  "Safari bloque la caméra sur cette page : ouvre l'adresse en https:// (scanne le QR code affiché dans Régie).": 'Safari blocks the camera on this page: open the https:// address (scan the QR code shown in Régie).',
  'Régie ne répond pas ({error}). Vérifie que Régie est ouverte et que le téléphone est sur le même Wi-Fi.': "Régie doesn't respond ({error}). Check that Régie is open and that the phone is on the same Wi-Fi.",
  'Régie a répondu {status}': 'Régie answered {status}',
  // messages envoyés par le serveur de Régie
  'Code incorrect : scanne le QR code affiché dans Régie.': 'Wrong code: scan the QR code shown in Régie.',
  'session terminée': 'session ended',
});
