// Texte animé (et Pancarte) en anglais : texte français (index.html, app.js, render.js) → anglais.
I18N.add({
  // barre, aperçu, antenne
  'Pancarte': 'Pancarte',
  'Hors antenne': 'Off air',
  "À l'écran": 'On screen',
  'Afficher la pancarte': 'Show Pancarte',
  'Masquer la pancarte': 'Hide Pancarte',
  "affiche / masque depuis n'importe où": 'show / hide from anywhere',
  'raccourci déjà pris par une autre app': 'shortcut already taken by another app',
  "Dans Discord, partage <b>l'écran entier</b>. En partage de fenêtre, la pancarte n'apparaît pas.": "In Discord, share your <b>entire screen</b>. When sharing a window, Pancarte doesn't show up.",
  'Aperçu': 'Preview',
  "Écran où la pancarte s'affiche": 'Screen where Pancarte is shown',
  'Écran {n}': 'Screen {n}',
  'principal': 'main',
  'Position rapide': 'Quick position',
  'Voile': 'Dim',
  "Assombrit tout l'écran derrière le texte": 'Darkens the whole screen behind the text',
  "Rejouer l'entrée": 'Replay entrance',
  "Rejouer l'animation d'entrée": 'Replay the entrance animation',
  'Glisse le texte pour le placer · le fond à damier sera transparent': 'Drag the text to place it · the checkerboard will be transparent',

  // texte, sous-titre, minuteur
  'Texte': 'Text',
  '{n} car.': '{n} chars',
  'Écris ton message…': 'Write your message…',
  'Rapide': 'Quick',
  'BRB': 'BRB',
  'Je reviens': 'Back soon',
  'Sous la douche': 'In the shower',
  'À table': 'Eating',
  'Pause': 'Break',
  'AFK': 'AFK',
  '2 minutes': '2 minutes',
  'Ne partez pas': "Don't leave",
  'Sous-titre': 'Subtitle',
  'Afficher le sous-titre': 'Show the subtitle',
  'Une précision, une excuse…': 'A detail, an excuse…',
  'Majuscules': 'Uppercase',
  'AA': 'AA',
  'Ombre': 'Shadow',
  'Ombre portée pour la lisibilité': 'Drop shadow for readability',
  'Taille': 'Size',
  'Minuteur': 'Timer',
  'Relancer': 'Restart',
  'Repartir de zéro (quand la pancarte est affichée)': 'Start over (when Pancarte is shown)',
  'Aucun': 'None',
  'Compte à rebours': 'Countdown',
  'Chrono': 'Stopwatch',
  'Libellé': 'Label',
  'min': 'min',

  // texte par défaut (render.js)
  'Je reviens vite': 'Be right back',
  'parti prendre une douche': 'taking a shower',
  'De retour dans': 'Back in',

  // styles
  'Styles': 'Styles',
  'survole pour animer': 'hover to animate',
  'Mes styles': 'My styles',
  'Enregistrer': 'Save',
  'OK': 'OK',
  'Nom du style': 'Style name',
  'Style {n}': 'Style {n}',
  'Supprimer ce style': 'Delete this style',
  'Règle un style à ta façon puis enregistre-le ici.': 'Tune a style your way, then save it here.',
  'WordArt 97': 'WordArt 97',
  'Néon': 'Neon',
  'Arcade': 'Arcade',
  'Chrome': 'Chrome',
  'Lingot': 'Gold bar',
  'Chewing-gum': 'Bubblegum',
  'Marqueur': 'Marker',
  'Miami': 'Miami',
  'Glitch': 'Glitch',
  'Bédé': 'Comic',
  'Gros titre': 'Headline',
  'Givre': 'Frost',

  // typographie
  'Typographie': 'Typography',
  'Autre police installée…': 'Other installed font…',
  "Nom exact d'une police installée": 'Exact name of an installed font',
  'Espacement': 'Spacing',
  'Interligne': 'Line height',
  'Inclinaison': 'Tilt',
  'Courbure': 'Curve',
  'Gauche': 'Left',
  'Centre': 'Center',
  'Droite': 'Right',
  'Italique': 'Italic',
  'I': 'I',

  // remplissage, contour, ombre
  'Remplissage': 'Fill',
  'Uni': 'Solid',
  'Dégradé': 'Gradient',
  'Or': 'Gold',
  'Arc-en-ciel': 'Rainbow',
  'Angle': 'Angle',
  'Reflet qui passe': 'Passing shine',
  'Couleurs qui tournent': 'Cycling colors',
  'Contour': 'Outline',
  'Épaisseur': 'Width',
  'Couleur': 'Color',
  'Ombre & relief': 'Shadow & depth',
  'Aucune': 'None',
  'Douce': 'Soft',
  'Dure': 'Hard',
  'Relief 3D': '3D extrusion',
  'Lueur': 'Glow',
  'Opacité': 'Opacity',
  'Profondeur': 'Depth',
  'Direction': 'Direction',
  'Flou': 'Blur',
  'Autre…': 'Other…',
  'Sélecteur du système': 'System picker',

  // animation
  'Animation': 'Animation',
  'Flotter': 'Float',
  'Pulsation': 'Pulse',
  'Balancier': 'Swing',
  'Vague': 'Wave',
  'Rebond': 'Bounce',
  'Gélatine': 'Jelly',
  'Tremblement': 'Shake',
  'Toupie': 'Spin',
  'Machine à écrire': 'Typewriter',
  'Défilement': 'Marquee',
  'Vitesse': 'Speed',
  'Amplitude': 'Amplitude',
  'Entrée': 'Entrance',
  'Directe': 'Instant',
  'Fondu': 'Fade',
  'Pop': 'Pop',
  'Montée': 'Rise',
  'Mise au point': 'Focus',
  'Lettre à lettre': 'Letter by letter',
});
