// Interface de SceneCue en anglais : texte français (tel qu'écrit dans index.html et scenecue.js) → anglais.
I18N.add({
  'SceneCue': 'SceneCue',
  'Hors antenne': 'Off air',
  "Langue de l'interface": 'Interface language',
  'Aperçu': 'Preview',
  "À l'écran": 'On screen',
  "À l'écran : {name}": 'On screen: {name}',
  'Scène vide': 'Empty scene',
  'Aucune scène': 'No scene',
  'Scènes': 'Scenes',
  'Nouvelle scène': 'New scene',
  'Calques': 'Layers',
  'Ajouter un module à la scène': 'Add a module to the scene',
  'Le calque du haut passe devant les autres.': 'The top layer is drawn over the others.',
  'Sortie': 'Output',
  "Écran où les scènes s'affichent": 'Screen where scenes are shown',
  'Diffusion': 'Broadcast',
  "Par-dessus l'écran, ou sur une copie de l'écran affichée sur un autre écran : ton écran reste dégagé": 'Over the screen, or on a copy of the screen shown on another screen: your screen stays clear',
  "Par-dessus l'écran": 'Over the screen',
  "Copie sur l'écran {n}": 'Copy on screen {n}',
  "Dans Discord, partage <b>l'écran {n}</b> · {size} en entier : le son passe avec. Tout ce que tu y poses est diffusé, sauf SceneCue.": 'In Discord, share <b>screen {n}</b> · {size} in full: the sound comes along. Anything you put on it is broadcast, except SceneCue.',
  "Dans Discord, partage <b>l'écran {n}</b> en entier.": 'In Discord, share <b>screen {n}</b> in full.',
  'Écran virtuel': 'Virtual screen',
  "Impossible d'allumer l'écran virtuel : {error}": "Can't turn the virtual screen on: {error}",
  "Allumage de l'écran virtuel…": 'Turning the virtual screen on…',
  "Dans Discord, partage <b>l'écran virtuel</b> · {size} en entier : sa vignette montre ta scène, et le son passe avec. SceneCue l'allume tant que ce réglage est choisi, et l'éteint en quittant.": 'In Discord, share the <b>virtual screen</b> · {size} in full: its thumbnail shows your scene, and the sound comes along. SceneCue turns it on while this setting is chosen, and off when it quits.',
  "Dans Discord, partage <b>l'écran virtuel</b> en entier.": 'In Discord, share the <b>virtual screen</b> in full.',
  'Écran {n}': 'Screen {n}',
  'Écran principal': 'Main screen',
  'Ajoute un premier module': 'Add a first module',
  'Chaque module devient un calque de la scène. Tu peux en empiler plusieurs.': 'Each module becomes a layer of the scene. You can stack several.',
  "Mettre à l'écran": 'Put on screen',
  "Mettre « {name} » à l'écran": 'Put “{name}” on screen',
  'Couper': 'Cut',
  'Couper « {name} »': 'Cut “{name}”',
  'Passer à « {name} »': 'Switch to “{name}”',
  'afficher / couper': 'show / cut',
  'scène n°': 'scene #',
  "Dans Discord, partage <b>l'écran entier</b>.": 'In Discord, share your <b>entire screen</b>.',
  'Supprimer ?': 'Delete?',
  'Dupliquer la scène': 'Duplicate scene',
  'Supprimer la scène': 'Delete scene',
  'Afficher le calque': 'Show layer',
  'Masquer le calque': 'Hide layer',
  'Dupliquer le calque': 'Duplicate layer',
  'Supprimer le calque': 'Delete layer',
  '{name} (copie)': '{name} (copy)',
  'Le module « {name} » est introuvable': 'Module “{name}” not found',
  "« {name} » n'a encore aucun calque": '“{name}” has no layers yet',
  'Crée une scène pour commencer': 'Create a scene to get started',
  'Aucun module trouvé.': 'No module found.',
  'Aucun module trouvé. Un module est un dossier avec un module.json, placé à côté de SceneCue.': 'No module found. A module is a folder with a module.json, placed next to SceneCue.',
});
