// Interface de Régie en anglais : texte français (tel qu'écrit dans index.html et regie.js) → anglais.
I18N.add({
  'Régie': 'Régie',
  'Hors antenne': 'Off air',
  "Langue de l'interface": 'Interface language',
  'Aperçu': 'Preview',
  "À l'écran": 'On screen',
  "À l'écran : {name}": 'On screen: {name}',
  'Scène vide': 'Empty scene',
  'Aucune scène': 'No scene',
  'Scènes': 'Scenes',
  'Nouvelle scène': 'New scene',
  'Calques': 'Layers',
  'Ajouter un module à la scène': 'Add a module to the scene',
  'Le calque du haut passe devant les autres.': 'The top layer is drawn over the others.',
  'Sortie': 'Output',
  "Écran où les scènes s'affichent": 'Screen where scenes are shown',
  'Écran {n}': 'Screen {n}',
  'Écran principal': 'Main screen',
  'Ajoute un premier module': 'Add a first module',
  'Chaque module devient un calque de la scène. Tu peux en empiler plusieurs.': 'Each module becomes a layer of the scene. You can stack several.',
  "Mettre à l'écran": 'Put on screen',
  "Mettre « {name} » à l'écran": 'Put “{name}” on screen',
  'Couper': 'Cut',
  'Couper « {name} »': 'Cut “{name}”',
  'Passer à « {name} »': 'Switch to “{name}”',
  'afficher / couper': 'show / cut',
  'scène n°': 'scene #',
  "Dans Discord, partage <b>l'écran entier</b>.": 'In Discord, share your <b>entire screen</b>.',
  'Supprimer ?': 'Delete?',
  'Dupliquer la scène': 'Duplicate scene',
  'Supprimer la scène': 'Delete scene',
  'Afficher le calque': 'Show layer',
  'Masquer le calque': 'Hide layer',
  'Dupliquer le calque': 'Duplicate layer',
  'Supprimer le calque': 'Delete layer',
  '{name} (copie)': '{name} (copy)',
  'Le module « {name} » est introuvable': 'Module “{name}” not found',
  "« {name} » n'a encore aucun calque": '“{name}” has no layers yet',
  'Crée une scène pour commencer': 'Create a scene to get started',
  'Aucun module trouvé.': 'No module found.',
  'Aucun module trouvé. Un module est un dossier avec un module.json, placé à côté de Régie.': 'No module found. A module is a folder with a module.json, placed next to Régie.',
});
